/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

import javax.swing.JOptionPane;

/**
 *
 * @author Brian Murphy
 * @reference http://www.youtube.com/watch?v=AYkC3WNbTuo
 */
public class BinaryCalculator extends javax.swing.JFrame {

    /**
     * Creates new form BinaryCalculator
     */
    public BinaryCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        btnLearning = new javax.swing.JButton();
        btnDisability = new javax.swing.JButton();
        btnMaths = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        lblBinaryT = new javax.swing.JLabel();
        btnDectoBin = new javax.swing.JButton();
        lblBinary = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);

        btnLearning.setBackground(new java.awt.Color(0, 0, 0));
        btnLearning.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnLearning.setForeground(new java.awt.Color(255, 255, 255));
        btnLearning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning.png"))); // NOI18N
        btnLearning.setContentAreaFilled(false);
        btnLearning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLearning.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning2.png"))); // NOI18N

        btnDisability.setBackground(new java.awt.Color(0, 0, 0));
        btnDisability.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnDisability.setForeground(new java.awt.Color(255, 255, 255));
        btnDisability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability.png"))); // NOI18N
        btnDisability.setContentAreaFilled(false);
        btnDisability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDisability.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability2.png"))); // NOI18N

        btnMaths.setBackground(new java.awt.Color(0, 0, 0));
        btnMaths.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnMaths.setForeground(new java.awt.Color(255, 255, 255));
        btnMaths.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths.png"))); // NOI18N
        btnMaths.setContentAreaFilled(false);
        btnMaths.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaths.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths2.png"))); // NOI18N
        btnMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMathsActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home2.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton.png"))); // NOI18N
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton2.png"))); // NOI18N
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnMaths, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMaths, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDisability, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnGoBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3.setBounds(10, 450, 370, 50);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBinaryT.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblBinaryT.setForeground(new java.awt.Color(255, 255, 255));
        lblBinaryT.setText("Binary  ");
        lblBinaryT.setBounds(210, 20, 160, 50);
        jLayeredPane1.add(lblBinaryT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDectoBin.setBackground(new java.awt.Color(255, 255, 255));
        btnDectoBin.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnDectoBin.setForeground(new java.awt.Color(0, 51, 204));
        btnDectoBin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/decimaltobin1.png"))); // NOI18N
        btnDectoBin.setContentAreaFilled(false);
        btnDectoBin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/decimaltobin2.png"))); // NOI18N
        btnDectoBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDectoBinActionPerformed(evt);
            }
        });
        btnDectoBin.setBounds(80, 100, 230, 60);
        jLayeredPane1.add(btnDectoBin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBinary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/binary.jpg"))); // NOI18N
        lblBinary.setBounds(90, 180, 210, 230);
        jLayeredPane1.add(lblBinary, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblContent.setText("jLabel1");
        lblContent.setBounds(10, 90, 370, 340);
        jLayeredPane1.add(lblContent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblMenu.setBounds(10, 450, 380, 50);
        jLayeredPane1.add(lblMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        lblBackground.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMathsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
       
    }//GEN-LAST:event_btnMathsActionPerformed

    private void btnDectoBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDectoBinActionPerformed
        // TODO add your handling code here:
        String y = "";
        String a = JOptionPane.showInputDialog("Enter number here to convert into Binary");
        int x = Integer.parseInt(a);
        int num = x;
        
        while (num>0)
        {
            int z = num % 2;
            y = " " + z + y;
            num = (num - z) / 2;
        }


        JOptionPane.showMessageDialog(null, "The result is: " + y);
    if(a == null || y == null){
            System.out.println("Cancel presed");

    }
    }//GEN-LAST:event_btnDectoBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BinaryCalculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDectoBin;
    private javax.swing.JButton btnDisability;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLearning;
    private javax.swing.JButton btnMaths;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBinary;
    private javax.swing.JLabel lblBinaryT;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
