/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

import javax.swing.JOptionPane;

/**
 *
 * @author Brian Murphy
 */
public class ComputingSupport extends javax.swing.JFrame {

    /**
     * Creates new form ComputingSupport
     */
    public ComputingSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ContentsPanel = new javax.swing.JPanel();
        btnExtaClasses = new javax.swing.JButton();
        btnExtaRevision = new javax.swing.JButton();
        btnMoodle = new javax.swing.JButton();
        btnBinaryCalculator = new javax.swing.JButton();
        btnContactUs = new javax.swing.JButton();
        btnRent = new javax.swing.JButton();
        btnFacebook = new javax.swing.JButton();
        btnTwitter = new javax.swing.JButton();
        btnYouTube = new javax.swing.JButton();
        lblContentCS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLearning = new javax.swing.JButton();
        btnDisability = new javax.swing.JButton();
        btnMaths = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        lblExamPapers = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computing Support");
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContentsPanel.setOpaque(false);

        btnExtaClasses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/extraclasses1.png"))); // NOI18N
        btnExtaClasses.setContentAreaFilled(false);
        btnExtaClasses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExtaClasses.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/extraclasses2.png"))); // NOI18N
        btnExtaClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtaClassesActionPerformed(evt);
            }
        });

        btnExtaRevision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/revision1.png"))); // NOI18N
        btnExtaRevision.setContentAreaFilled(false);
        btnExtaRevision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExtaRevision.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/revision2.png"))); // NOI18N
        btnExtaRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtaRevisionActionPerformed(evt);
            }
        });

        btnMoodle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/moodle1.png"))); // NOI18N
        btnMoodle.setContentAreaFilled(false);
        btnMoodle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoodle.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/moodle2.png"))); // NOI18N
        btnMoodle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoodleActionPerformed(evt);
            }
        });

        btnBinaryCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/binary1.png"))); // NOI18N
        btnBinaryCalculator.setContentAreaFilled(false);
        btnBinaryCalculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBinaryCalculator.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/binary2.png"))); // NOI18N
        btnBinaryCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinaryCalculatorActionPerformed(evt);
            }
        });

        btnContactUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/contactus.png"))); // NOI18N
        btnContactUs.setContentAreaFilled(false);
        btnContactUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContactUs.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/contactus2.png"))); // NOI18N
        btnContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactUsActionPerformed(evt);
            }
        });

        btnRent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/book1.png"))); // NOI18N
        btnRent.setContentAreaFilled(false);
        btnRent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRent.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/book2.png"))); // NOI18N
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });

        btnFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/facebook.gif"))); // NOI18N
        btnFacebook.setContentAreaFilled(false);
        btnFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacebook.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/facebook2.gif"))); // NOI18N
        btnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacebookActionPerformed(evt);
            }
        });

        btnTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/twitter.png"))); // NOI18N
        btnTwitter.setContentAreaFilled(false);
        btnTwitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTwitter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/twitter2.png"))); // NOI18N
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });

        btnYouTube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/youtube.jpg"))); // NOI18N
        btnYouTube.setContentAreaFilled(false);
        btnYouTube.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/youtube2.png"))); // NOI18N
        btnYouTube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYouTubeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentsPanelLayout = new javax.swing.GroupLayout(ContentsPanel);
        ContentsPanel.setLayout(ContentsPanelLayout);
        ContentsPanelLayout.setHorizontalGroup(
            ContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMoodle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBinaryCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRent, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExtaClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExtaRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(ContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacebook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTwitter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYouTube, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ContentsPanelLayout.setVerticalGroup(
            ContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentsPanelLayout.createSequentialGroup()
                .addGroup(ContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentsPanelLayout.createSequentialGroup()
                        .addComponent(btnExtaClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnExtaRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentsPanelLayout.createSequentialGroup()
                        .addComponent(btnMoodle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBinaryCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentsPanelLayout.createSequentialGroup()
                        .addComponent(btnRent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentsPanelLayout.createSequentialGroup()
                        .addComponent(btnYouTube, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ContentsPanel.setBounds(10, 80, 380, 370);
        jLayeredPane1.add(ContentsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblContentCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblContentCS.setBounds(10, 75, 380, 370);
        jLayeredPane1.add(lblContentCS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setOpaque(false);

        btnLearning.setBackground(new java.awt.Color(0, 0, 0));
        btnLearning.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnLearning.setForeground(new java.awt.Color(255, 255, 255));
        btnLearning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning.png"))); // NOI18N
        btnLearning.setContentAreaFilled(false);
        btnLearning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLearning.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning2.png"))); // NOI18N

        btnDisability.setBackground(new java.awt.Color(0, 0, 0));
        btnDisability.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnDisability.setForeground(new java.awt.Color(255, 255, 255));
        btnDisability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability.png"))); // NOI18N
        btnDisability.setContentAreaFilled(false);
        btnDisability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDisability.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability2.png"))); // NOI18N

        btnMaths.setBackground(new java.awt.Color(0, 0, 0));
        btnMaths.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnMaths.setForeground(new java.awt.Color(255, 255, 255));
        btnMaths.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths.png"))); // NOI18N
        btnMaths.setContentAreaFilled(false);
        btnMaths.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaths.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths2.png"))); // NOI18N
        btnMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMathsActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home2.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btnMaths, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMaths, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBounds(10, 440, 370, 60);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblMenu.setBounds(10, 450, 380, 50);
        jLayeredPane1.add(lblMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblExamPapers.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblExamPapers.setForeground(new java.awt.Color(255, 255, 255));
        lblExamPapers.setText("Computing");
        lblExamPapers.setBounds(190, 20, 186, 48);
        jLayeredPane1.add(lblExamPapers, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExtaClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtaClassesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ExtraClasses exc = new ExtraClasses();
        exc.setVisible(true);
    }//GEN-LAST:event_btnExtaClassesActionPerformed

    private void btnExtaRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtaRevisionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ExtraRevision exr = new ExtraRevision();
        exr.setVisible(true);
    }//GEN-LAST:event_btnExtaRevisionActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnMoodleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoodleActionPerformed
        // TODO add your handling code here:
        try {
            String URL = "https://moodle.ncirl.ie/course/view.php?id=1199";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnMoodleActionPerformed

    private void btnMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMathsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
      
    }//GEN-LAST:event_btnMathsActionPerformed

    private void btnBinaryCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinaryCalculatorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BinaryCalculator bc = new BinaryCalculator();
        bc.setVisible(true);
        
    }//GEN-LAST:event_btnBinaryCalculatorActionPerformed

    private void btnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookActionPerformed
        // TODO add your handling code here:
        try {
 String URL = "https://www.facebook.com/NCIRL?fref=ts";
 java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

} catch (Exception e) {
 JOptionPane.showMessageDialog(null, e.getMessage());
 }
    }//GEN-LAST:event_btnFacebookActionPerformed

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
        // TODO add your handling code here:
        try {
 String URL = "https://twitter.com/NCIRL";
 java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

} catch (Exception e) {
 JOptionPane.showMessageDialog(null, e.getMessage());
 }
    }//GEN-LAST:event_btnTwitterActionPerformed

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RentGUI r = new RentGUI();
        r.setVisible(true);
    }//GEN-LAST:event_btnRentActionPerformed

    private void btnContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactUsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactUs cu = new ContactUs();
        cu.setVisible(true);
    }//GEN-LAST:event_btnContactUsActionPerformed

    private void btnYouTubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYouTubeActionPerformed
        // TODO add your handling code here:
        try {
            String URL = "https://moodle.ncirl.ie/course/view.php?id=1199";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

                   
    }//GEN-LAST:event_btnYouTubeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ComputingSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentsPanel;
    private javax.swing.JButton btnBinaryCalculator;
    private javax.swing.JButton btnContactUs;
    private javax.swing.JButton btnDisability;
    private javax.swing.JButton btnExtaClasses;
    private javax.swing.JButton btnExtaRevision;
    private javax.swing.JButton btnFacebook;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLearning;
    private javax.swing.JButton btnMaths;
    private javax.swing.JButton btnMoodle;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JButton btnYouTube;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblContentCS;
    private javax.swing.JLabel lblExamPapers;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
