/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

/**
 * ExtraClassesMaths.java 20/04/2013
 *
 * @author Ben Callaghan
 */
public class ExtraClassesMaths extends javax.swing.JFrame {

    /**
     * Creates new form ExtraClasses
     */
    public ExtraClassesMaths() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnLearning1 = new javax.swing.JButton();
        btnDisability1 = new javax.swing.JButton();
        btnComputing1 = new javax.swing.JButton();
        btnHome1 = new javax.swing.JButton();
        btnGoBack1 = new javax.swing.JButton();
        ExtraClasses = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Html", "14:00", "TBC", "scr3", "S.Cogan"},
                {"Html", "16:00", "TBC", "scr1", "S.Cogan"},
                {"Oop", "12:00", "TBC", "scr2", "F.Sheridan"},
                {"Oop", "17:00", "TBC", "scr3", "F.Sheridan"},
                {"Ops", "15:00", "TBC", "scr3", "E.Nolan"},
                {"Ops", "09:00", "TBC", "scr1", "E.Nolan"},
                {"Multimedia", "10:00", "TBC", "scr2", "L.Deasy"},
                {"Multimedia", "13:00", "TBC", "scr1", "L.Deasy"},
                {"Comp Arch", "14:00", "TBC", "Blab", "S.Cogan"},
                {"Comp Arch", "10:00", "TBC", "Blab", "S.Cogan"},
                {"Mfis", "13:00", "TBC", "scr3", "L.Donaldson"},
                {"Mfis", "11:00", "TBC", "scr2", "L.Donaldson"},
                {"Maths", "09:00", "TBC", "3.01", "J.Lambert"},
                {"Maths", "12:00", "TBC", "3.02", "J.Lambert"},
                {"Computing", "15:00", "TBC", "scr1", "L.Deasy"},
                {"Computing", "17:00", "TBC", "scr2", "L.Deasy"}
            },
            new String [] {
                "Module", "Time", "Date", "Classroom", "Lecturer"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(20, 100, 340, 280);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setOpaque(false);

        btnLearning1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnLearning1.setForeground(new java.awt.Color(102, 153, 255));
        btnLearning1.setText("Learning");
        btnLearning1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearning1ActionPerformed(evt);
            }
        });

        btnDisability1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnDisability1.setForeground(new java.awt.Color(102, 153, 255));
        btnDisability1.setText("Disablity");
        btnDisability1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisability1ActionPerformed(evt);
            }
        });

        btnComputing1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnComputing1.setForeground(new java.awt.Color(102, 153, 255));
        btnComputing1.setText("Computing");
        btnComputing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputing1ActionPerformed(evt);
            }
        });

        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome1.setContentAreaFilled(false);
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        btnGoBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton.png"))); // NOI18N
        btnGoBack1.setContentAreaFilled(false);
        btnGoBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComputing1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLearning1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisability1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnDisability1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLearning1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnComputing1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnHome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBounds(10, 450, 381, 50);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ExtraClasses.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        ExtraClasses.setForeground(new java.awt.Color(255, 255, 255));
        ExtraClasses.setText("Extra Classes");
        ExtraClasses.setBounds(160, 20, 200, 50);
        jLayeredPane1.add(ExtraClasses, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        lblBackground.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComputing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputing1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);
    }//GEN-LAST:event_btnComputing1ActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void btnGoBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
    }//GEN-LAST:event_btnGoBack1ActionPerformed

    private void btnLearning1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearning1ActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_btnLearning1ActionPerformed

    private void btnDisability1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisability1ActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_btnDisability1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtraClassesMaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtraClassesMaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtraClassesMaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtraClassesMaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ExtraClassesMaths().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExtraClasses;
    private javax.swing.JButton btnComputing1;
    private javax.swing.JButton btnDisability1;
    private javax.swing.JButton btnGoBack1;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnLearning1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
