package studentservices;

import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brian Murphy
 */
public class ExtraRevision extends javax.swing.JFrame {

    /**
     * Creates new form ExtraRevision
     */
    public ExtraRevision() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHTML = new javax.swing.JButton();
        btnComputers = new javax.swing.JButton();
        btnMaths = new javax.swing.JButton();
        btnComputerArc = new javax.swing.JButton();
        MFIS = new javax.swing.JButton();
        OOP = new javax.swing.JButton();
        btnOpsSystems = new javax.swing.JButton();
        btnDatabase = new javax.swing.JButton();
        btnIntroProg = new javax.swing.JButton();
        btnDataCom = new javax.swing.JButton();
        lblExamPapers = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLearning = new javax.swing.JButton();
        btnDisability = new javax.swing.JButton();
        btnMaths2 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMaximizedBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        btnHTML.setText("HTML 2012");
        btnHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTMLActionPerformed(evt);
            }
        });

        btnComputers.setText("Computers 2012");
        btnComputers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputersActionPerformed(evt);
            }
        });

        btnMaths.setText("Maths");
        btnMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMathsActionPerformed(evt);
            }
        });

        btnComputerArc.setText("Computer Arc");
        btnComputerArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputerArcActionPerformed(evt);
            }
        });

        MFIS.setText("MFIS");
        MFIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFISActionPerformed(evt);
            }
        });

        OOP.setText("OOP");
        OOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OOPActionPerformed(evt);
            }
        });

        btnOpsSystems.setText("Ops Systems");
        btnOpsSystems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpsSystemsActionPerformed(evt);
            }
        });

        btnDatabase.setText("Database");
        btnDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatabaseActionPerformed(evt);
            }
        });

        btnIntroProg.setText("Intro to Prog");
        btnIntroProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroProgActionPerformed(evt);
            }
        });

        btnDataCom.setText("Data Comm");
        btnDataCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataComActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComputers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaths, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComputerArc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHTML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MFIS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpsSystems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDatabase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OOP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIntroProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDataCom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHTML)
                    .addComponent(MFIS)
                    .addComponent(btnOpsSystems))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComputers)
                    .addComponent(btnDatabase)
                    .addComponent(btnIntroProg))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaths)
                    .addComponent(OOP)
                    .addComponent(btnDataCom))
                .addGap(33, 33, 33)
                .addComponent(btnComputerArc)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 210));

        lblExamPapers.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblExamPapers.setForeground(new java.awt.Color(255, 255, 255));
        lblExamPapers.setText("Exam Papers");
        getContentPane().add(lblExamPapers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 200, 40));

        lblContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblContent.setText("jLabel4");
        getContentPane().add(lblContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 360));

        jPanel3.setOpaque(false);

        btnLearning.setBackground(new java.awt.Color(0, 0, 0));
        btnLearning.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnLearning.setForeground(new java.awt.Color(255, 255, 255));
        btnLearning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning.png"))); // NOI18N
        btnLearning.setContentAreaFilled(false);
        btnLearning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLearning.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning2.png"))); // NOI18N
        btnLearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearningActionPerformed(evt);
            }
        });

        btnDisability.setBackground(new java.awt.Color(0, 0, 0));
        btnDisability.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnDisability.setForeground(new java.awt.Color(255, 255, 255));
        btnDisability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability.png"))); // NOI18N
        btnDisability.setContentAreaFilled(false);
        btnDisability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDisability.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability2.png"))); // NOI18N

        btnMaths2.setBackground(new java.awt.Color(0, 0, 0));
        btnMaths2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnMaths2.setForeground(new java.awt.Color(255, 255, 255));
        btnMaths2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths.png"))); // NOI18N
        btnMaths2.setContentAreaFilled(false);
        btnMaths2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaths2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths2.png"))); // NOI18N
        btnMaths2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaths2ActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home2.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton.png"))); // NOI18N
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton2.png"))); // NOI18N
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnMaths2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDisability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnMaths2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 380, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHTMLActionPerformed
        // TODO add your handling code here:
      try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "xhtml.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnHTMLActionPerformed

    private void btnComputersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputersActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\computers.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnComputersActionPerformed

    private void btnMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMathsActionPerformed
        // TODO add your handling code here:
         try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\Desktop\\"
                    + "StudentServices\\src\\studentservices\\maths.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
        
    }//GEN-LAST:event_btnMathsActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);

    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnMaths2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaths2ActionPerformed
        // TODO add your handling code here: 
        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
    }//GEN-LAST:event_btnMaths2ActionPerformed

    private void btnLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLearningActionPerformed

    private void OOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OOPActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "oop.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_OOPActionPerformed

    private void btnIntroProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroProgActionPerformed
        // TODO add your handling code here:
         try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "introprog.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
        
    }//GEN-LAST:event_btnIntroProgActionPerformed

    private void MFISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFISActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "mfis.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_MFISActionPerformed

    private void btnOpsSystemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpsSystemsActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "ops.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnOpsSystemsActionPerformed

    private void btnDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatabaseActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "databases.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnDatabaseActionPerformed

    private void btnComputerArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputerArcActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "comparc.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnComputerArcActionPerformed

    private void btnDataComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataComActionPerformed
        // TODO add your handling code here:
        try
        {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"C:\\Users\\Brian Murphy\\"
                    + "Desktop\\StudentServices\\src\\studentservices\\"
                    + "datacom.pdf");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnDataComActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtraRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtraRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtraRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtraRevision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ExtraRevision().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MFIS;
    private javax.swing.JButton OOP;
    private javax.swing.JButton btnComputerArc;
    private javax.swing.JButton btnComputers;
    private javax.swing.JButton btnDataCom;
    private javax.swing.JButton btnDatabase;
    private javax.swing.JButton btnDisability;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnHTML;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnIntroProg;
    private javax.swing.JButton btnLearning;
    private javax.swing.JButton btnMaths;
    private javax.swing.JButton btnMaths2;
    private javax.swing.JButton btnOpsSystems;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblExamPapers;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
