/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian Murphy
 */
public class Login extends javax.swing.JDialog {

    String fname;
    String lname;
    String uname;
    String pword;
    private ArrayList<User> list = new ArrayList();

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtUname = new javax.swing.JTextField();
        lblUname = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(460, 210, 0, 0));
        setResizable(false);

        txtUname.setBounds(100, 20, 140, 30);
        jLayeredPane1.add(txtUname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblUname.setText("Student ID:");
        lblUname.setBounds(20, 20, 70, 30);
        jLayeredPane1.add(lblUname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblPassword.setText("Password:");
        lblPassword.setBounds(20, 60, 80, 30);
        jLayeredPane1.add(lblPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnClear.setBounds(100, 100, 60, 23);
        jLayeredPane1.add(btnClear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnLogin.setText("Login ");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.setBounds(170, 100, 70, 23);
        jLayeredPane1.add(btnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtPassword.setBounds(100, 60, 140, 30);
        jLayeredPane1.add(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblBackground.setBounds(0, 0, 250, 150);
        jLayeredPane1.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        if (this.validateUser() == true) {
            System.out.println("username validated");
            this.setVisible(false);
            StudentForm sf = new StudentForm();
            sf.setVisible(true);


        } else {

            txtPassword.setText("");
            txtUname.setText("");
            JOptionPane.showMessageDialog(null, "Invalid username or password", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtUname.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnClearActionPerformed
    public boolean validateUser() {
        String fname1 = "Brian";
        String lname1 = "Murphy";
        String uname1 = "x12533897";
        String pword1 = "brian";

        String fname2 = "Frances";
        String lname2 = "Sheridan";
        String uname2 = "x1234455";
        String pword2 = "frances";

        String fname3 = "Ciaran";
        String lname3 = "Browne";
        String uname3 = "x12375786";
        String pword3 = "ciaran";

        String fname4 = "Ben";
        String lname4 = "Callaghan";
        String uname4 = "x12112241";
        String pword4 = "ben";

        String fname5 = "James";
        String lname5 = "Cosgrave";
        String uname5 = "x12345678";
        String pword5 = "james";

        String fname6 = "Aaron";
        String lname6 = "Kane";
        String uname6 = "x12445678";
        String pword6 = "aaron";

        String fname7 = "Sam";
        String lname7 = "Gormley";
        String uname7 = "x12545678";
        String pword7 = "sam";

        String fname8 = "Aodhan";
        String lname8 = "Scott";
        String uname8 = "x12645678";
        String pword8 = "aodhan";

        String fname9 = "Ryan";
        String lname9 = "Scollard";
        String uname9 = "x12745678";
        String pword9 = "ryan";

        String fname10 = "Conor";
        String lname10 = "Graham";
        String uname10 = "x12845678";
        String pword10 = "conor";

        String fname11 = "Sean";
        String lname11 = "Keeley";
        String uname11 = "x12945678";
        String pword11 = "sean";

        String fname12 = "Brian";
        String lname12 = "Kinsella";
        String uname12 = "x12955678";
        String pword12 = "briank";

        String fname13 = "Joe";
        String lname13 = "Bloggs";
        String uname13 = "x12964567";
        String pword13 = "sam";

        String fname14 = "Peter";
        String lname14 = "Packets";
        String uname14 = "x1294778";
        String pword14 = "peter";

        String fname15 = "Bob";
        String lname15 = "Squash";
        String uname15 = "x12943678";
        String pword15 = "bob";


        User us1 = new User(fname1, lname1, uname1, pword1);
        User us2 = new User(fname2, lname2, uname2, pword2);
        User us3 = new User(fname3, lname3, uname3, pword3);
        User us4 = new User(fname4, lname4, uname4, pword4);
        User us5 = new User(fname5, lname5, uname5, pword5);
        User us6 = new User(fname6, lname6, uname6, pword6);
        User us7 = new User(fname7, lname7, uname7, pword7);
        User us8 = new User(fname8, lname8, uname8, pword8);
        User us9 = new User(fname9, lname9, uname9, pword9);
        User us10 = new User(fname10, lname10, uname10, pword10);
        User us11 = new User(fname11, lname11, uname11, pword11);
        User us12 = new User(fname12, lname12, uname12, pword12);
        User us13 = new User(fname13, lname13, uname13, pword13);
        User us14 = new User(fname14, lname14, uname14, pword14);
        User us15 = new User(fname15, lname15, uname15, pword15);


        list.add(us1);
        list.add(us2);
        list.add(us3);
        list.add(us4);
        list.add(us5);
        list.add(us6);
        list.add(us7);
        list.add(us8);
        list.add(us9);
        list.add(us10);
        list.add(us11);
        list.add(us12);
        list.add(us13);
        list.add(us14);
        list.add(us15);




        uname = txtUname.getText().toLowerCase();
        pword = txtPassword.getText().toLowerCase();

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getUsername().equals(uname) && list.get(i).getPassword().equals(pword)) {


                return true;
            }

        }


        return false;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
