 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

import javax.swing.JOptionPane;

/**
 * MathsSupport.java 20/04/2013
 *
 * @reference
 * http://stackoverflow.com/questions/6448993/launching-and-closing-a-native-browser-that-points-to-web-app
 * Facebook and Twitter buttons
 * @author Ben Callaghan
 */
public class MathsSupport extends javax.swing.JFrame {

    /**
     * Creates new form MathsGUI
     */
    public MathsSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnLearning = new javax.swing.JButton();
        btnDisability = new javax.swing.JButton();
        btnComputing = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        Notes = new javax.swing.JButton();
        LecturerInfo = new javax.swing.JButton();
        Calculator = new javax.swing.JButton();
        ExtraClasses = new javax.swing.JButton();
        ContactUs = new javax.swing.JButton();
        Facebook = new javax.swing.JButton();
        xandogame = new javax.swing.JButton();
        Signup = new javax.swing.JButton();
        Twitter = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MathsSupport = new javax.swing.JLabel();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);

        btnLearning.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnLearning.setForeground(new java.awt.Color(102, 153, 255));
        btnLearning.setText("Learning");
        btnLearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearningActionPerformed(evt);
            }
        });

        btnDisability.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnDisability.setForeground(new java.awt.Color(102, 153, 255));
        btnDisability.setText("Disablity");
        btnDisability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisabilityActionPerformed(evt);
            }
        });

        btnComputing.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnComputing.setForeground(new java.awt.Color(102, 153, 255));
        btnComputing.setText("Computing");
        btnComputing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputingActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton.png"))); // NOI18N
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComputing, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLearning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnDisability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLearning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnComputing, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 390, -1));

        Notes.setForeground(new java.awt.Color(102, 153, 255));
        Notes.setText("Notes");
        Notes.setOpaque(false);
        Notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesActionPerformed(evt);
            }
        });
        getContentPane().add(Notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 130, 30));

        LecturerInfo.setForeground(new java.awt.Color(102, 153, 255));
        LecturerInfo.setText("Lecturer Info");
        LecturerInfo.setOpaque(false);
        LecturerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecturerInfoActionPerformed(evt);
            }
        });
        getContentPane().add(LecturerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, 30));

        Calculator.setForeground(new java.awt.Color(102, 153, 255));
        Calculator.setText("Calculator");
        Calculator.setToolTipText("");
        Calculator.setOpaque(false);
        Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorActionPerformed(evt);
            }
        });
        getContentPane().add(Calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, 30));

        ExtraClasses.setForeground(new java.awt.Color(102, 153, 255));
        ExtraClasses.setText("Extra Classes");
        ExtraClasses.setOpaque(false);
        ExtraClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraClassesActionPerformed(evt);
            }
        });
        getContentPane().add(ExtraClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 130, 30));

        ContactUs.setForeground(new java.awt.Color(102, 153, 255));
        ContactUs.setText("Contact");
        ContactUs.setOpaque(false);
        ContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsActionPerformed(evt);
            }
        });
        getContentPane().add(ContactUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 90, 30));

        Facebook.setForeground(new java.awt.Color(102, 153, 255));
        Facebook.setText("Facebook");
        Facebook.setOpaque(false);
        Facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacebookActionPerformed(evt);
            }
        });
        getContentPane().add(Facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 90, 30));

        xandogame.setForeground(new java.awt.Color(102, 153, 255));
        xandogame.setText("X&O's ");
        xandogame.setOpaque(false);
        xandogame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xandogameActionPerformed(evt);
            }
        });
        getContentPane().add(xandogame, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 90, 30));

        Signup.setForeground(new java.awt.Color(102, 153, 255));
        Signup.setText("Signup");
        Signup.setOpaque(false);
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        getContentPane().add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, 30));

        Twitter.setForeground(new java.awt.Color(102, 153, 255));
        Twitter.setText("Twitter");
        Twitter.setOpaque(false);
        Twitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwitterActionPerformed(evt);
            }
        });
        getContentPane().add(Twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 90, 30));

        btnExit.setForeground(new java.awt.Color(102, 153, 255));
        btnExit.setText("Exit");
        btnExit.setPreferredSize(new java.awt.Dimension(63, 23));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/Mathematics.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 370, 180));

        MathsSupport.setBackground(new java.awt.Color(0, 0, 0));
        MathsSupport.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        MathsSupport.setForeground(new java.awt.Color(255, 255, 255));
        MathsSupport.setText("Maths Support");
        getContentPane().add(MathsSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 240, 60));

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        getContentPane().add(Backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesActionPerformed
        this.setVisible(false);
        RevisionNotes ns = new RevisionNotes();
        ns.setVisible(true);  // TODO add your handling code here:

    }//GEN-LAST:event_NotesActionPerformed

    private void LecturerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecturerInfoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LecturerInfo li = new LecturerInfo();
        li.setVisible(true);
    }//GEN-LAST:event_LecturerInfoActionPerformed

    private void FacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacebookActionPerformed
        // @reference http://stackoverflow.com/questions/6448993/launching-and-closing-a-native-browser-that-points-to-web-app
        try {
            String URL = "https://facebook.com/NCIRL";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_FacebookActionPerformed

    private void ContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactUs cc = new ContactUs();
        cc.setVisible(true);

    }//GEN-LAST:event_ContactUsActionPerformed

    private void ExtraClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraClassesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ExtraClassesMaths ecc = new ExtraClassesMaths();
        ecc.setVisible(true);
    }//GEN-LAST:event_ExtraClassesActionPerformed

    private void CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Calculator cc = new Calculator();
        cc.setVisible(true);
    }//GEN-LAST:event_CalculatorActionPerformed

    private void xandogameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xandogameActionPerformed
        this.setVisible(false);
        XandOGame xo = new XandOGame();
        xo.setVisible(true);        // TODO add your handling code here: java.awt.Desktop.getDesktop().browse(theURI);I mght be abloe to use this code
    }//GEN-LAST:event_xandogameActionPerformed

    private void btnComputingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);
    }//GEN-LAST:event_btnComputingActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void TwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwitterActionPerformed
        try {
            String URL = "https://twitter.com/NCIRL";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } //@reference http://stackoverflow.com/questions/6448993/launching-and-closing-a-native-browser-that-points-to-web-app
    }//GEN-LAST:event_TwitterActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to EXIT the program?",
                "Choose",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_SignupActionPerformed

    private void btnLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearningActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_btnLearningActionPerformed

    private void btnDisabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisabilityActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_btnDisabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*
         * try { for (javax.swing.UIManager.LookAndFeelInfo info :
         * javax.swing.UIManager.getInstalledLookAndFeels()) { if
         * ("Nimbus".equals(info.getName())) {
         * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } }
         * } catch (ClassNotFoundException ex) {
         * java.util.logging.Logger.getLogger(MathsGUI.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); } catch (InstantiationException ex) {
         * java.util.logging.Logger.getLogger(MathsGUI.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); } catch (IllegalAccessException ex) {
         * java.util.logging.Logger.getLogger(MathsGUI.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         * java.util.logging.Logger.getLogger(MathsGUI.class.getName()).log(java.util.logging.Level.SEVERE,
         * null, ex); } //</editor-fold>
         */
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MathsSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround;
    private javax.swing.JButton Calculator;
    private javax.swing.JButton ContactUs;
    private javax.swing.JButton ExtraClasses;
    private javax.swing.JButton Facebook;
    private javax.swing.JButton LecturerInfo;
    private javax.swing.JLabel MathsSupport;
    private javax.swing.JButton Notes;
    private javax.swing.JButton Signup;
    private javax.swing.JButton Twitter;
    private javax.swing.JButton btnComputing;
    private javax.swing.JButton btnDisability;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLearning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton xandogame;
    // End of variables declaration//GEN-END:variables
}
