/*
 * MathsNotes.java
 * 20/04/2013
 * @Author Ben Callaghan
 * @refernce import code http://forums.netbeans.org/topic5234.html
 * @refernce export code http://stackoverflow.com/questions/13440566/saving-file-in-same-format-as-textarea-prob
 */
package studentservices;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * 20/04/2013
 *
 * @author Ben Callaghan
 */
public class MathsNotes extends javax.swing.JFrame {

    /**
     * Creates new form MathsExamPaper
     */
    public MathsNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotesTf = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        ViewNotes = new javax.swing.JButton();
        SaveNotes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLearning = new javax.swing.JButton();
        btnDisability = new javax.swing.JButton();
        btnComputing = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(NotesTf);

        jScrollPane1.setBounds(20, 90, 360, 210);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notes");
        jLabel1.setBounds(210, 20, 150, 48);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ViewNotes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewNotes.setForeground(new java.awt.Color(102, 153, 255));
        ViewNotes.setText("View Notes");
        ViewNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewNotesActionPerformed(evt);
            }
        });
        ViewNotes.setBounds(20, 330, 130, 30);
        jLayeredPane1.add(ViewNotes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SaveNotes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SaveNotes.setForeground(new java.awt.Color(102, 153, 255));
        SaveNotes.setText("Save");
        SaveNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNotesActionPerformed(evt);
            }
        });
        SaveNotes.setBounds(260, 330, 120, 30);
        jLayeredPane1.add(SaveNotes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setOpaque(false);

        btnLearning.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnLearning.setForeground(new java.awt.Color(102, 153, 255));
        btnLearning.setText("Learning");
        btnLearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearningActionPerformed(evt);
            }
        });

        btnDisability.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnDisability.setForeground(new java.awt.Color(102, 153, 255));
        btnDisability.setText("Disablity");
        btnDisability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisabilityActionPerformed(evt);
            }
        });

        btnComputing.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnComputing.setForeground(new java.awt.Color(102, 153, 255));
        btnComputing.setText("Computing");
        btnComputing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputingActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton.png"))); // NOI18N
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComputing, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnDisability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLearning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnComputing, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBounds(10, 430, 370, 50);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        lblBackground.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, -1, 400, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComputingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);
    }//GEN-LAST:event_btnComputingActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void SaveNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNotesActionPerformed
// This allows you to choose the file save location:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String Notes = NotesTf.getText();
        //@refernce http://stackoverflow.com/questions/13440566/saving-file-in-same-format-as-textarea-prob
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("./"));
        int actionDialog = chooser.showSaveDialog(this);
        if (actionDialog == JFileChooser.APPROVE_OPTION) {
            try {
                outFile = new File("MathsNotes.txt");
                fw = new FileWriter(outFile, true);
                bw = new BufferedWriter(fw);
                if (Notes == null) {
                    return;
                }
                if (outFile.exists()) {
                    actionDialog = JOptionPane.showConfirmDialog(this,
                            "Replace existing file?");
                    if (actionDialog == JOptionPane.NO_OPTION) {
                        return;
                    }
                }
                bw = new BufferedWriter(new FileWriter(outFile));
                bw.write(Notes);
                bw.close(); // after first checking if null
                JOptionPane.showMessageDialog(null, "Your notes have been saved successfully");
                //File fileName = new File(chooser.getSelectedFile( ) + "" );

            } catch (IOException e) {
                System.out.println("Error writing to file: " + e);
            }
        }
    }//GEN-LAST:event_SaveNotesActionPerformed

    private void ViewNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewNotesActionPerformed
        // File would not print to text field so use of modified code was used
        //*http://forums.netbeans.org/topic5234.html
        //*        


        File inFile;
        FileReader fr;
        BufferedReader br;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("./"));
        int returnVal = chooser.showOpenDialog(ViewNotes);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            FileInputStream in = null;
            String Notes = "MathsNotes.txt";
            try {

                in = new FileInputStream(Notes);
                BufferedInputStream bin = new BufferedInputStream(in);
                ByteArrayOutputStream bout = new ByteArrayOutputStream();

                int iread = -1;
                while ((iread = bin.read()) != -1) {
                    bout.write(iread);
                }


                String Note = new String(bout.toByteArray());


                NotesTf.setText(Note);

            } catch (Throwable e) {//catch everything

                System.err.println(e);
                e.printStackTrace(System.err);
            } finally {

                try {
                    in.close();
                } catch (Throwable e) {
                }
            }
        }
    }//GEN-LAST:event_ViewNotesActionPerformed

    private void btnLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearningActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_btnLearningActionPerformed

    private void btnDisabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisabilityActionPerformed
                 // TODO add your handling code here:
    }//GEN-LAST:event_btnDisabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MathsNotes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane NotesTf;
    private javax.swing.JButton SaveNotes;
    private javax.swing.JButton ViewNotes;
    private javax.swing.JButton btnComputing;
    private javax.swing.JButton btnDisability;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLearning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
