/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian Murphy
 * @reference Frances Sheridan, Youtube
 */
public class RentGUI extends javax.swing.JFrame {
    
    private ArrayList <Rent> aList;
    private String Student, BookName, BookCategory;
    int count;

    /**
     * Creates new form RentGUI
     */
    public RentGUI() {
        initComponents();
        aList = new ArrayList<>();
        Student = new String();
        BookName = new String();
        BookCategory = new String();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        lblStudent = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        lblBookCategory = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        txtBookName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        btnRent = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLearning = new javax.swing.JButton();
        btnDisability = new javax.swing.JButton();
        btnMaths2 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        lblMenu = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Booking");
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMaximizedBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMaximumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        lblStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblStudent.setText("Student ID:");

        lblBookName.setForeground(new java.awt.Color(255, 255, 255));
        lblBookName.setText("Book Name:");

        lblBookCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblBookCategory.setText("Book Category:");

        btnRent.setText("Rent Book");
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });

        btnDisplay.setText("Display all books");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnSearch.setText("Search by Category");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReturn.setText("Return Book");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnSave.setText("Save ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/book.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookCategory)
                            .addComponent(lblBookName)
                            .addComponent(lblStudent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategory)
                            .addComponent(txtBookName)
                            .addComponent(txtStudent)))
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookName)
                            .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudent)
                            .addComponent(btnRent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisplay)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(lblBookCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addComponent(jLabel1))
                .addGap(21, 21, 21))
        );

        jPanel1.setBounds(10, 100, 380, 340);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblContent.setBounds(10, 100, 380, 340);
        jLayeredPane1.add(lblContent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setOpaque(false);

        btnLearning.setBackground(new java.awt.Color(0, 0, 0));
        btnLearning.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnLearning.setForeground(new java.awt.Color(255, 255, 255));
        btnLearning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning.png"))); // NOI18N
        btnLearning.setContentAreaFilled(false);
        btnLearning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLearning.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning2.png"))); // NOI18N
        btnLearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearningActionPerformed(evt);
            }
        });

        btnDisability.setBackground(new java.awt.Color(0, 0, 0));
        btnDisability.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnDisability.setForeground(new java.awt.Color(255, 255, 255));
        btnDisability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability.png"))); // NOI18N
        btnDisability.setContentAreaFilled(false);
        btnDisability.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDisability.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability2.png"))); // NOI18N

        btnMaths2.setBackground(new java.awt.Color(0, 0, 0));
        btnMaths2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnMaths2.setForeground(new java.awt.Color(255, 255, 255));
        btnMaths2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths.png"))); // NOI18N
        btnMaths2.setContentAreaFilled(false);
        btnMaths2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaths2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths2.png"))); // NOI18N
        btnMaths2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaths2ActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home2.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton.png"))); // NOI18N
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton2.png"))); // NOI18N
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnMaths2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDisability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnMaths2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBounds(10, 450, 385, 50);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblMenu.setBounds(10, 450, 380, 50);
        jLayeredPane1.add(lblMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        lblBackground.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
        Student = txtStudent.getText();
        BookName = txtBookName.getText();
        BookCategory = txtCategory.getText();
        
        Rent r = new Rent();
        r.setStudent(Student);
        r.setBookName(BookName);
        r.setBookCategory(BookCategory);
        
        aList.add(r);
        
        count++;

    }//GEN-LAST:event_btnRentActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        
        for(int i = 0; i < aList.size(); i++){
            JOptionPane.showMessageDialog(null, "Student ID: "+aList.get(i).getStudent() 
                    +"\n Book Name: "+aList.get(i).getBookName()+"\n Book Category:"+aList.get(i).getBookCategory());
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String SearchCategory = JOptionPane.showInputDialog(null, "Please enter the Book Category you want to search");
        
        for(int i = 0; i < aList.size();) {
            if(SearchCategory.equalsIgnoreCase(aList.get(i).getBookCategory())) {
                JOptionPane.showMessageDialog(null, "Student ID:" +aList.get(i).getStudent()
                        + "\n Book Name:"+aList.get(i).getBookName()+ "\n Book Category:"+aList.get(i).getBookCategory());
            }
        
        
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        if(txtStudent.getText().equals("")||txtBookName.getText().equals("")|| 
                txtCategory.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must enter your Student ID, Book Name and Category to delete");
        }
        else if(count ==0){
            JOptionPane.showMessageDialog(null, "Sorry there are no Books to delete ath this time");
        }
        else{
            Student = txtStudent.getText();
            BookName = txtBookName.getText();
            BookCategory = txtCategory.getText();
            
            for(int i = 0; i < aList.size(); i++){
                if(aList.get(i).getStudent().equals(Student)&&aList.get(i).getBookName().equals(BookName)
                        &&aList.get(i).getBookCategory().equals(BookCategory)) {
                    aList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null, "Your booking has been cancelled"+i);
                    break;
                }
                if(i==count-1){
                   JOptionPane.showMessageDialog(null,"Sorry that book could not be found"); 
                }
              }
          }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLearningActionPerformed

    private void btnMaths2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaths2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
    }//GEN-LAST:event_btnMaths2ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Student = txtStudent.getText();
        BookName = txtBookName.getText();
        BookCategory = txtCategory.getText();
        
        Rent r = new Rent();
        r.setStudent(Student);
        r.setBookName(BookName);
        r.setBookCategory(BookCategory);
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("rentedbooks.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(aList);
            
            JOptionPane.showMessageDialog(null, "Your session was saved successfully");
            
            oStream.close();
            
            
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RentGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisability;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLearning;
    private javax.swing.JButton btnMaths2;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBookCategory;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables
}
