/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

/**
 * RevisionNotes.java 20/04/2013
 *
 * @author Ben Callaghan
 */
public class RevisionNotes extends javax.swing.JFrame {

    /**
     * Creates new form ExamRevision
     */
    public RevisionNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        RevisionImage = new javax.swing.JLabel();
        ExamRevision = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLearning = new javax.swing.JButton();
        btnDisability = new javax.swing.JButton();
        btnComputing = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnGoBack1 = new javax.swing.JButton();
        btnExamRevision = new javax.swing.JButton();
        Notes = new javax.swing.JButton();
        Mep2012 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RevisionImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ben\\Desktop\\revisions-calendar.jpg")); // NOI18N
        RevisionImage.setBounds(20, 80, 360, 220);
        jLayeredPane1.add(RevisionImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ExamRevision.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        ExamRevision.setForeground(new java.awt.Color(255, 255, 255));
        ExamRevision.setText("Revision Notes");
        ExamRevision.setBounds(150, 20, 250, 60);
        jLayeredPane1.add(ExamRevision, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setOpaque(false);

        btnLearning.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnLearning.setForeground(new java.awt.Color(102, 153, 255));
        btnLearning.setText("Learning");
        btnLearning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearningActionPerformed(evt);
            }
        });

        btnDisability.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnDisability.setForeground(new java.awt.Color(102, 153, 255));
        btnDisability.setText("Disablity");
        btnDisability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisabilityActionPerformed(evt);
            }
        });

        btnComputing.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnComputing.setForeground(new java.awt.Color(102, 153, 255));
        btnComputing.setText("Computing");
        btnComputing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputingActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/home.png"))); // NOI18N
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnGoBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/backbutton.png"))); // NOI18N
        btnGoBack1.setContentAreaFilled(false);
        btnGoBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComputing, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisability, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGoBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnDisability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLearning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnComputing, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBounds(0, 450, 400, 50);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnExamRevision.setForeground(new java.awt.Color(102, 153, 255));
        btnExamRevision.setText("Contact Us");
        btnExamRevision.setBorder(null);
        btnExamRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamRevisionActionPerformed(evt);
            }
        });
        btnExamRevision.setBounds(120, 310, 100, 30);
        jLayeredPane1.add(btnExamRevision, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Notes.setForeground(new java.awt.Color(102, 153, 255));
        Notes.setText("Notes");
        Notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesActionPerformed(evt);
            }
        });
        Notes.setBounds(20, 310, 90, 30);
        jLayeredPane1.add(Notes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Mep2012.setForeground(new java.awt.Color(102, 153, 255));
        Mep2012.setText("Maths Exam paper 2012");
        Mep2012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mep2012ActionPerformed(evt);
            }
        });
        Mep2012.setBounds(230, 310, 150, 30);
        jLayeredPane1.add(Mep2012, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        lblBackground.setBounds(0, 0, 400, 500);
        jLayeredPane1.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExamRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamRevisionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ContactUs cu = new ContactUs();
        cu.setVisible(true);
    }//GEN-LAST:event_btnExamRevisionActionPerformed

    private void Mep2012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mep2012ActionPerformed
        this.setVisible(false);
        MathsExamPaper mr = new MathsExamPaper();
        mr.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_Mep2012ActionPerformed

    private void btnComputingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);
    }//GEN-LAST:event_btnComputingActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentForm st = new StudentForm();
        st.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGoBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBack1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
    }//GEN-LAST:event_btnGoBack1ActionPerformed

    private void NotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesActionPerformed
        this.setVisible(false);
        MathsNotes mn = new MathsNotes();
        mn.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_NotesActionPerformed

    private void btnLearningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearningActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_btnLearningActionPerformed

    private void btnDisabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisabilityActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_btnDisabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisionNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisionNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisionNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisionNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RevisionNotes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExamRevision;
    private javax.swing.JButton Mep2012;
    private javax.swing.JButton Notes;
    private javax.swing.JLabel RevisionImage;
    private javax.swing.JButton btnComputing;
    private javax.swing.JButton btnDisability;
    private javax.swing.JButton btnExamRevision;
    private javax.swing.JButton btnGoBack1;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLearning;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
