/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentservices;

import javax.swing.JOptionPane;

/**
 *
 * @author x12533897
 */
public class StudentForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentFormLayer = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        btnComputingSupport = new javax.swing.JButton();
        lblComputingSupport = new javax.swing.JLabel();
        btnMathsSupport = new javax.swing.JButton();
        lblMathsSupport = new javax.swing.JLabel();
        btnLearning = new javax.swing.JButton();
        lblLearningDevelopment = new javax.swing.JLabel();
        btnDisabilitySupport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblStudentServices = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMaximizedBounds(new java.awt.Rectangle(450, 200, 400, 500));
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentFormLayer.setMaximumSize(new java.awt.Dimension(400, 500));

        jPanel1.setOpaque(false);

        btnComputingSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/compsupport.jpg"))); // NOI18N
        btnComputingSupport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComputingSupport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/compsupport2.jpg"))); // NOI18N
        btnComputingSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputingSupportActionPerformed(evt);
            }
        });

        lblComputingSupport.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblComputingSupport.setForeground(new java.awt.Color(255, 255, 255));
        lblComputingSupport.setText("Computing Support");

        btnMathsSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths.jpg"))); // NOI18N
        btnMathsSupport.setText("jButton1");
        btnMathsSupport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMathsSupport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/maths2.jpg"))); // NOI18N
        btnMathsSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMathsSupportActionPerformed(evt);
            }
        });

        lblMathsSupport.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblMathsSupport.setForeground(new java.awt.Color(255, 255, 255));
        lblMathsSupport.setText("Maths Support");

        btnLearning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learningd.jpg"))); // NOI18N
        btnLearning.setContentAreaFilled(false);
        btnLearning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLearning.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Brian Murphy\\Desktop\\learning2.jpg")); // NOI18N

        lblLearningDevelopment.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblLearningDevelopment.setForeground(new java.awt.Color(255, 255, 255));
        lblLearningDevelopment.setText("Learning Development");

        btnDisabilitySupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/disability.jpg"))); // NOI18N
        btnDisabilitySupport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDisabilitySupport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/learning2.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Learning Development");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComputingSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblComputingSupport))
                            .addComponent(btnMathsSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblMathsSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLearningDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisabilitySupport, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLearning, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnComputingSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputingSupport)
                    .addComponent(lblLearningDevelopment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDisabilitySupport, javax.swing.GroupLayout.PREFERRED_SIZE, 152, Short.MAX_VALUE)
                        .addGap(270, 270, 270))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMathsSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMathsSupport)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.setBounds(20, 100, 360, 380);
        StudentFormLayer.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/blue.png"))); // NOI18N
        lblMenu.setBounds(10, 100, 380, 380);
        StudentFormLayer.add(lblMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnExit.setBounds(320, 490, 74, 30);
        StudentFormLayer.add(btnExit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnBack.setBackground(new java.awt.Color(0, 176, 0));
        btnBack.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Go Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        btnBack.setBounds(10, 490, 101, 30);
        StudentFormLayer.add(btnBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblStudentServices.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        lblStudentServices.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentServices.setText("Student Services");
        lblStudentServices.setBounds(160, 40, 240, 50);
        StudentFormLayer.add(lblStudentServices, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentservices/background.png"))); // NOI18N
        lblBackground.setOpaque(true);
        lblBackground.setBounds(0, 20, 400, 500);
        StudentFormLayer.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(StudentFormLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 400, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to EXIT the program?",
                "Choose",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EntryScreen es = new EntryScreen();
        es.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnComputingSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputingSupportActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingSupport cs = new ComputingSupport();
        cs.setVisible(true);
    }//GEN-LAST:event_btnComputingSupportActionPerformed

    private void btnMathsSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMathsSupportActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MathsSupport ms = new MathsSupport();
        ms.setVisible(true);
      
    }//GEN-LAST:event_btnMathsSupportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * 
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane StudentFormLayer;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComputingSupport;
    private javax.swing.JButton btnDisabilitySupport;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLearning;
    private javax.swing.JButton btnMathsSupport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblComputingSupport;
    private javax.swing.JLabel lblLearningDevelopment;
    private javax.swing.JLabel lblMathsSupport;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblStudentServices;
    // End of variables declaration//GEN-END:variables
}